In [11]:
import requests
import pandas as pd
import numpy as np

In [28]:
# Import list of ICOs
file = 'list_of_features - ICOs_reddit.csv'
df1 = pd.read_csv(file)
df1.head()

              ICO  # Reddit Posts
0  RequestNetwork             986
1    ArkEcosystem             980
2         ETHLend             977
3  RebelliousCoin             976
4   RedPulseToken             951

### CryptoCompare

In [42]:
# GET request to CryptoCompare
response = requests.get("https://www.cryptocompare.com/api/data/coinlist/")
# Result comes back as a flat dict, transform to a list of dicts
data = []
for k,v in response.json()['Data'].items():
    data.append(v)
# Visualize as a dataframe 
df2 = pd.DataFrame(data)
df2.head()

,Algorithm,CoinName,FullName,FullyPremined,Id,ImageUrl,Name,PreMinedValue,ProofType,SortOrder,Sponsored,Symbol,TotalCoinSupply,TotalCoinsFreeFloat,Url
0,Scrypt,Dogecoin,Dogecoin (DOGE),0,4432,/media/19684/doge.png,DOGE,N/A,PoW,8,False,DOGE,N/A,N/A,/coins/doge/overview
1,Equihash,ZCash,ZCash (ZEC),0,24854,/media/351360/zec.png,ZEC,N/A,PoW,9,False,ZEC,21000000,N/A,/coins/zec/overview
2,SHA-512,Bitshares,Bitshares (BTS),1,5039,/media/20705/bts.png,BTS,N/A,PoS,10,False,BTS,2511953117,N/A,/coins/bts/overview
3,Multiple,DigiByte,DigiByte (DGB),0,4430,/media/12318264/7638-nty_400x400.jpg,DGB,N/A,PoW,11,False,DGB,21000000000,N/A,/coins/dgb/overview
4,SHA256,BitcoinDark,BitcoinDark (BTCD),0,4400,/media/19630/btcd_1.png,BTCD,N/A,PoW/PoS,13,False,BTCD,22000000,N/A,/coins/btcd/overview

### CryptoWatch

In [51]:
# GET request to CryptoCompare
response = requests.get("https://api.cryptowat.ch/assets")
data = response.json()['result']
df3 = pd.DataFrame(data)
df3.head()

    fiat   id        name                                  route symbol
0  False  404  FirstBlood    https://api.cryptowat.ch/assets/1st    1st
1  False  201        ICON    https://api.cryptowat.ch/assets/ICX    ICX
2  False  517   The Abyss  https://api.cryptowat.ch/assets/abyss  abyss
3  False  502    Alphacat   https://api.cryptowat.ch/assets/acat   acat
4  False  484      Achain    https://api.cryptowat.ch/assets/act    act

In [35]:
# Lowercase names
df1['coin_name'] = df1['ICO'].apply(lambda x: x.lower())
df2['coin_name'] = df2['CoinName'].apply(lambda x: x.lower())
df3['coin_name'] = df3['name'].apply(lambda x: x.lower())
# Compare
df = pd.merge(df1,df2,on='coin_name',how='left',indicator=True)

In [41]:
df3.groupby('_merge').aggregate('count')[['coin_name']]

            coin_name
_merge
left_only         368
right_only          0
both               91